baseURL: https://www.brycewray.com/
languageCode: en-us
title: BryceWray.com
theme: sass # choices are sass and twcss - as of 2023-01-11
timeZone: America/Chicago

# ignoreErrors:
#   - "error-remote-getjson"

summaryLength: 30 # words --- if you use summaries
FootnoteReturnLinkContents: "&#8593;"
enableRobotsTXT: true
enableGitInfo: true

timeout: "150s" # for the sake of newly generated images and such; default is `30s`

pygmentsUseClasses: true
pygmentsCodefences: true

Paginate: 5 # so five posts will appear on each page from "/posts"

params:
  Domain: "brycewray.com"
  Author: "Bryce Wray"
  AuthorEmail: "bw@brycewray.com"
  AuthorUrl: "https://www.brycewray.com/about/"
  AuthorAvatar: "https://www.brycewray.com/images/icons/apple-icon-1024x1024.png"
  Description: "Bryce Wrayâ€™s website | Observations, opinions, geekiness"
  Host: "CFP" # choices for Host are "CFP" and "Vercel"
  HostName: "Cloudflare Pages" # choices for HostName are "Cloudflare Pages" and "Vercel"
  HostURL: "https://pages.cloudflare.com" # choices for HostURL are "https://pages.cloudflare.com" and "https://vercel.com"
  SiteLive: true # Boolean --- used for adapting robots.txt as needed
  SearchTitle: "Search the site"
  # PublicSans: true # Boolean --- "true" triggers use of em dash space replacements

frontmatter:
  date:
    - date
    - publishDate
    - lastmod
  lastmod:
    - :git
    - lastmod
    - date
    - publishDate
  publishDate:
    - publishDate
    - date

markup:
  highlight:
    guessSyntax: true
    noClasses: false
    tabWidth: 2
  goldmark:
    extensions:
      linkify: false
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true # otherwise, can't use (e.g.) "Content" as a heading
      wrapStandAloneImageWithinParagraph: false
    renderer:
      unsafe: true
      # only to allow for inline HTML and/or JS
      # ... other desired settings are defaults

imaging: # Hugo defaults shown in comments
  # anchor: Smart # Smart
  # bgColor: '#ffffff' # '#ffffff'
  # hint: photo # photo
  # quality: 75 # 75
  # resampleFilter: MitchellNetravali # Box

disableKinds:
  - taxonomy
  - term
# ^^ keep it this way unless/until I config elsewhere appropriately

# taxonomies:
#   # category: categories
#   # series: series
#   tag: tags

privacy:
  twitter:
    simple: true

services:
  twitter:
    disableInlineCSS: true

# following is overridden in production by other config file
caches:
  getjson:
    dir: :resourceDir/json
    # maxAge: 144h # default = -1 (forever)
  getresource:
    dir: :resourceDir/_gen
    # maxAge: 144h # default = -1 (forever)

minify:
  disableJSON: true
  tdewolff:
    html:
      keepQuotes: true
      keepWhitespace: false # per https://discourse.gohugo.io/t/is-html-minification-broken/34174

outputFormats:
  json:
    baseName: "index"
    mediaType: "application/json"
    isPlainText: true

outputs:
  home:
    - html
    - rss
    - json
  section:
    - html
    - rss
    # - json # unneeded as of 2022-12-26

rssLimit: 10 # default is -1 (unlimited)
# setting of '10' conforms to Eleventy repo's handling

security:
  exec:
    allow:
      - ^dart-sass-embedded$
      - ^go$
      - ^npx$
      - ^postcss$
      - ^subl$
      - ^open$
  funcs:
    getenv:
      - ^*

# newContentEditor: open -b pro.writer.mac
# # h/t:
# # - https://www.lkhrs.com/blog/2022/10/hugo-ia-writer/
# # - https://discourse.gohugo.io/t/newcontenteditor-trouble-with-spaces/40930
