# baseURL = "https://example.com" # Change to your site URL and un-comment, of course
languageCode = "en-us" # Change if not appropriate for your site
title = "Site title goes here"

summaryLength = 30 # words --- if you use summaries
FootnoteReturnLinkContents = "&#8593;"
enableRobotsTXT = true

Paginate = 5 # so five posts will appear on each page from "/posts"

[params]
    Author = "Your name goes here"
    Description = "Your site description goes here"

[markup]
    [markup.goldmark]
      [markup.goldmark.renderer]
        unsafe = true # only to allow for inline HTML and/or JS
    [markup.highlight]
      guessSyntax = true
      noClasses = false

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        title = "Whatever you call your 'about' page"
        url = "/about/"
        weight = 100
    
    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        title = "This siteâ€™s posts"
        url = "/posts/"
        weight = 110
