caches:
  getjson:
    dir: :resourceDir/json
    maxAge: 0 # default = -1 (forever)
  getresource:
    dir: :resourceDir/_gen
    maxAge: 0 # default = -1 (forever)

disableKinds:
  - taxonomy
  - term
# ^^ keep it this way unless/until I config elsewhere appropriately
